export const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  RIDER_ASSIGNED: 'RIDER_ASSIGNED',
  PICKED_UP: 'PICKED_UP',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED',
  RETURNED: 'RETURNED',
  PARTIAL_DELIVERY: 'PARTIAL_DELIVERY',
};

export const USER_ROLES = {
  ADMIN: 'ADMIN',
  RIDER: 'RIDER',
  CUSTOMER: 'CUSTOMER',
};

// STRICT STATE TRANSITION MATRIX
// Maps current status -> valid next statuses allowed in normal workflow.

export const ALLOWED_TRANSITIONS = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.RIDER_ASSIGNED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.RIDER_ASSIGNED]: [ORDER_STATUS.PICKED_UP, ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PICKED_UP]: [ORDER_STATUS.IN_TRANSIT, ORDER_STATUS.FAILED],
  [ORDER_STATUS.IN_TRANSIT]: [ORDER_STATUS.OUT_FOR_DELIVERY, ORDER_STATUS.FAILED],
  [ORDER_STATUS.OUT_FOR_DELIVERY]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.FAILED, ORDER_STATUS.PARTIAL_DELIVERY],
  [ORDER_STATUS.PARTIAL_DELIVERY]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.FAILED, ORDER_STATUS.RETURNED],
  [ORDER_STATUS.FAILED]: [ORDER_STATUS.RETURNED, ORDER_STATUS.OUT_FOR_DELIVERY],
  [ORDER_STATUS.DELIVERED]: [],
  [ORDER_STATUS.CANCELLED]: [],
  [ORDER_STATUS.RETURNED]: [],
};